name: Release Plugin

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build plugin
        run: npm run build:prod

      - name: Debug - List files
        run: |
          echo "=== Current directory ==="
          ls -la
          echo "=== Blocks directory ==="
          ls -la blocks/ || echo "Blocks directory not found"
          echo "=== Assets directory ==="
          ls -la assets/ || echo "Assets directory not found"

      - name: Create ZIP file
        run: |
          # Create a temporary directory for the plugin
          mkdir -p temp

          # Copy main PHP file
          cp flexible-slider-and-carousel.php temp/
          echo "✅ Copied flexible-slider-and-carousel.php"

          # Copy blocks directory (kompilierte Block-Dateien)
          if [ -d "blocks" ]; then
            cp -r blocks temp/
            echo "✅ Copied blocks/ (compiled block files)"
          else
            echo "ERROR: Blocks directory not found!"
            exit 1
          fi

          # Copy assets directory (CSS/JS Assets)
          if [ -d "assets" ]; then
            cp -r assets temp/
            echo "✅ Copied assets/ (CSS/JS assets)"
          else
            echo "⚠️  Assets directory not found (optional)"
          fi

          # Copy documentation files
          for doc in README.md CHANGELOG.md LICENSE; do
            if [ -f "$doc" ]; then
              cp "$doc" temp/
              echo "✅ Copied $doc"
            else
              echo "⚠️  Documentation not found: $doc"
            fi
          done

          # Debug - List temp directory contents
          echo "=== Temp directory contents ==="
          ls -la temp/
          echo "=== Temp/blocks contents ==="
          ls -la temp/blocks/ || echo "Temp/blocks not found"
          echo "=== Temp/assets contents ==="
          ls -la temp/assets/ || echo "Temp/assets not found"

          # Create ZIP file from temp directory contents
          cd temp
          zip -r ../flexible-slider-and-carousel.zip .
          cd ..

          # Debug - Check ZIP contents
          echo "=== ZIP file contents ==="
          unzip -l flexible-slider-and-carousel.zip | head -20
          echo "..."
          unzip -l flexible-slider-and-carousel.zip | tail -10

          echo "✅ ZIP file created with only production files (no src/, webpack.config.js, etc.)"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: flexible-slider-and-carousel.zip
          generate_release_notes: true
          draft: false
          prerelease: false
          name: "Release ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
